# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalogue.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='catalogue.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63\x61talogue.proto\"W\n\x10\x43\x61talogueRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1d\n\x08\x63\x61tegory\x18\x05 \x01(\x0e\x32\x0b.GameStatus\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"\x98\x01\n\x17\x43\x61talogueRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tdeveloper\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\t\x12\r\n\x05\x63over\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\t\x12\x0c\n\x04sale\x18\x08 \x01(\t\"F\n\x11\x43\x61talogueResponse\x12\x31\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x18.CatalogueRecommendation*-\n\nGameStatus\x12\x07\n\x03NEW\x10\x00\x12\x0c\n\x08TRENDING\x10\x01\x12\x08\n\x04SALE\x10\x02\x32\x41\n\nCatalogues\x12\x33\n\nCatalogued\x12\x11.CatalogueRequest\x1a\x12.CatalogueResponseb\x06proto3'
)

_GAMESTATUS = _descriptor.EnumDescriptor(
  name='GameStatus',
  full_name='GameStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRENDING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SALE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=335,
  serialized_end=380,
)
_sym_db.RegisterEnumDescriptor(_GAMESTATUS)

GameStatus = enum_type_wrapper.EnumTypeWrapper(_GAMESTATUS)
NEW = 0
TRENDING = 1
SALE = 2



_CATALOGUEREQUEST = _descriptor.Descriptor(
  name='CatalogueRequest',
  full_name='CatalogueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='CatalogueRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='CatalogueRequest.category', index=1,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='CatalogueRequest.max_results', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=106,
)


_CATALOGUERECOMMENDATION = _descriptor.Descriptor(
  name='CatalogueRecommendation',
  full_name='CatalogueRecommendation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CatalogueRecommendation.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='CatalogueRecommendation.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='developer', full_name='CatalogueRecommendation.developer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='CatalogueRecommendation.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rating', full_name='CatalogueRecommendation.rating', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cover', full_name='CatalogueRecommendation.cover', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='CatalogueRecommendation.price', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sale', full_name='CatalogueRecommendation.sale', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=261,
)


_CATALOGUERESPONSE = _descriptor.Descriptor(
  name='CatalogueResponse',
  full_name='CatalogueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='CatalogueResponse.recommendations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=333,
)

_CATALOGUEREQUEST.fields_by_name['category'].enum_type = _GAMESTATUS
_CATALOGUERESPONSE.fields_by_name['recommendations'].message_type = _CATALOGUERECOMMENDATION
DESCRIPTOR.message_types_by_name['CatalogueRequest'] = _CATALOGUEREQUEST
DESCRIPTOR.message_types_by_name['CatalogueRecommendation'] = _CATALOGUERECOMMENDATION
DESCRIPTOR.message_types_by_name['CatalogueResponse'] = _CATALOGUERESPONSE
DESCRIPTOR.enum_types_by_name['GameStatus'] = _GAMESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CatalogueRequest = _reflection.GeneratedProtocolMessageType('CatalogueRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATALOGUEREQUEST,
  '__module__' : 'catalogue_pb2'
  # @@protoc_insertion_point(class_scope:CatalogueRequest)
  })
_sym_db.RegisterMessage(CatalogueRequest)

CatalogueRecommendation = _reflection.GeneratedProtocolMessageType('CatalogueRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _CATALOGUERECOMMENDATION,
  '__module__' : 'catalogue_pb2'
  # @@protoc_insertion_point(class_scope:CatalogueRecommendation)
  })
_sym_db.RegisterMessage(CatalogueRecommendation)

CatalogueResponse = _reflection.GeneratedProtocolMessageType('CatalogueResponse', (_message.Message,), {
  'DESCRIPTOR' : _CATALOGUERESPONSE,
  '__module__' : 'catalogue_pb2'
  # @@protoc_insertion_point(class_scope:CatalogueResponse)
  })
_sym_db.RegisterMessage(CatalogueResponse)



_CATALOGUES = _descriptor.ServiceDescriptor(
  name='Catalogues',
  full_name='Catalogues',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=382,
  serialized_end=447,
  methods=[
  _descriptor.MethodDescriptor(
    name='Catalogued',
    full_name='Catalogues.Catalogued',
    index=0,
    containing_service=None,
    input_type=_CATALOGUEREQUEST,
    output_type=_CATALOGUERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CATALOGUES)

DESCRIPTOR.services_by_name['Catalogues'] = _CATALOGUES

# @@protoc_insertion_point(module_scope)
